CREATE DATABASE PRODUCTSMANAGERS;
CREATE TABLE PRODUCTS(ID INT PRIMARY KEY AUTO_INCREMENT,
                      productCode VARCHAR(50),
                      productName VARCHAR(50),
                      productPrice INT,
                      productAmount INT,
                      productDescription VARCHAR(200),
                      productStatus BIT
);
INSERT INTO  PRODUCTS(
    productCode,
    productName,
    productPrice,
    productAmount,
    productDescription,
    productStatus)
VALUES('A004','b40',666,26,"1VS100",0);

CREATE UNIQUE INDEX index_product
    ON PRODUCTS (ProductCode);
EXPLAIN SELECT*FROM PRODUCTS WHERE PRODUCTCODE ='A004';
ALTER TABLE PRODUCTS DROP INDEX INDEX_PRODUCT;

CREATE INDEX index_product
    ON PRODUCTS (productName,productPrice);
EXPLAIN SELECT*FROM PRODUCTS WHERE PRODUCTNAME ='AK47' OR PRODUCTPRICE<133;

CREATE VIEW INFOPRODUCT AS
SELECT productCode, productName, productPrice, productStatus
FROM PRODUCTS ;
DROP VIEW INFOPRODUCT;

DELIMITER $
CREATE PROCEDURE DISPLAYALLINFOPRODUCT()
BEGIN
SELECT*FROM PRODUCTS;
END $

CALL DISPLAYALLINFOPRODUCT()

DELIMITER $
CREATE PROCEDURE ADDPRODUCT
(IN PCODE VARCHAR(30), PNAME VARCHAR(30),PPRICE INT,PAMOUNT INT,PDESCRIPTION VARCHAR(100),PSTATUS BIT)
BEGIN
INSERT INTO PRODUCTS(productCode,productName,productPrice,productAmount,productDescription,productStatus)
VALUES(PCODE,PNAME,PPRICE,PAMOUNT,PDESCRIPTION,PSTATUS);
END $


CALL ADDPRODUCT('A005','M700',100,11,'1VS2',0);

DELIMITER $
CREATE PROCEDURE FIXINFOPRODUCT
(IN PID INT , PNAME VARCHAR(30),PPRICE INT,PAMOUNT INT,PDESCRIPTION VARCHAR(100),PSTATUS BIT)
BEGIN
UPDATE PRODUCTS
SET
    productName=PNAME,
    productPrice=PPRICE,
    productAmount=PAMOUNT,
    productDescription=PDESCRIPTION,
    productStatus=PSTATUS
WHERE ID=PID;
END $
CALL FIXINFOPRODUCT(4,'B41',444,4,'1VSALL',1)


DELIMITER $
CREATE PROCEDURE DELETEPRODUCT
(IN PID INT)
BEGIN
DELETE FROM PRODUCTS
WHERE ID =PID;
END $

CALL DELETEPRODUCT(5)